### ISSUE TITLE
Logger Service

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/dalla-stats2#2]
Needs to connect to Router through the API module.
- Get stats every x minutes
- Insert stats into the database
- Update tables
- Trigger Events

**Comment by CDuPlooy** [comment]
I know a cron.hourly isn't exactly every x minutes but it's a decent interval  👍

**Comment by egeldenhuys** [comment]
That will definitely be simpler than to setup a systemd service and a daemon!
